{% set name = "pybamm" %}
{% set version = "23.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7a8b1be89b7cad3e08033905b9fb37ca7a4824611ccbcb10cb5b58a1c3f393f

build:
  number: 0
  entry_points:
    - pybamm_install_odes = pybamm.install_odes:main
    - pybamm_install_jax = pybamm.util:install_jax
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py<38 or py>311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - wheel
  run:
    - anytree >=2.4.3
    - autograd >=1.2
    - casadi >=3.6.0
    - imageio >=2.9.0
    - matplotlib-base >=2.0
    - numpy >=1.16
    - pandas >=0.24
    - pybtex >=0.24.0
    - python
    - scikit-fem >=0.2.0
    - scipy >=1.3
    - sympy >=1.8
    - tqdm
    - xarray

test:
  imports:
    - pybamm
    - pybamm.discretisations
    - pybamm.experiment
    - pybamm.expression_tree
    - pybamm.expression_tree.operations
    - pybamm.expression_tree.printing
    - pybamm.geometry
    - pybamm.meshes
    - pybamm.models
    - pybamm.models.full_battery_models
    - pybamm.models.full_battery_models.equivalent_circuit
    - pybamm.models.full_battery_models.lead_acid
    - pybamm.models.full_battery_models.lithium_ion
    - pybamm.models.full_battery_models.lithium_metal
    - pybamm.models.submodels
    - pybamm.models.submodels.active_material
    - pybamm.models.submodels.convection
    - pybamm.models.submodels.convection.through_cell
    - pybamm.models.submodels.convection.transverse
    - pybamm.models.submodels.current_collector
    - pybamm.models.submodels.electrode
    - pybamm.models.submodels.electrode.ohm
    - pybamm.models.submodels.electrolyte_conductivity
    - pybamm.models.submodels.electrolyte_conductivity.surface_potential_form
    - pybamm.models.submodels.electrolyte_diffusion
    - pybamm.models.submodels.equivalent_circuit_elements
    - pybamm.models.submodels.external_circuit
    - pybamm.models.submodels.interface
    - pybamm.models.submodels.interface.interface_utilisation
    - pybamm.models.submodels.interface.kinetics
    - pybamm.models.submodels.interface.kinetics.inverse_kinetics
    - pybamm.models.submodels.interface.lithium_plating
    - pybamm.models.submodels.interface.open_circuit_potential
    - pybamm.models.submodels.interface.sei
    - pybamm.models.submodels.oxygen_diffusion
    - pybamm.models.submodels.particle
    - pybamm.models.submodels.particle_mechanics
    - pybamm.models.submodels.porosity
    - pybamm.models.submodels.thermal
    - pybamm.models.submodels.thermal.pouch_cell
    - pybamm.models.submodels.transport_efficiency
    - pybamm.parameters
    - pybamm.plotting
    - pybamm.solvers
    - pybamm.solvers.c_solvers
    - pybamm.spatial_methods
    - pybamm.step
  commands:
    - pybamm_install_odes --help  # [not win]
    - pybamm_install_jax --help

about:
  home: https://github.com/pybamm-team/PyBaMM
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Battery Mathematical Modelling.
  doc_url: https://docs.pybamm.org/en/latest
  dev_url: https://github.com/pybamm-team/PyBaMM

extra:
  recipe-maintainers:
    - agriyakhetarpal
    - tinosulzer
    - priyanshuone6
    - tlestang
