{% set name = "pybamm" %}
{% set version = "21.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 299ff83b790db4e3c0cb2dfef05ee4938d80d6e368e67d5e403bbd1f58a6367a

build:
  number: 0
  entry_points:
    - pybamm_edit_parameter = pybamm.parameters_cli:edit_parameter
    - pybamm_add_parameter = pybamm.parameters_cli:add_parameter
    - pybamm_list_parameters = pybamm.parameters_cli:list_parameters
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win]
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
  run:
    - anytree >=2.4.3
    - autograd >=1.2
    - casadi >=3.5.0
    - jupyter
    - matplotlib-base >=2.0
    - numpy >=1.16
    - pandas >=0.24
    - python
    - scikit-fem >=0.2.0
    - scipy >=1.3

test:
  imports:
    - pybamm
    - pybamm.discretisations
    - pybamm.experiments
    - pybamm.expression_tree
    - pybamm.expression_tree.operations
    - pybamm.geometry
    - pybamm.meshes
    - pybamm.models
    - pybamm.models.full_battery_models
    - pybamm.models.full_battery_models.lead_acid
    - pybamm.models.full_battery_models.lithium_ion
    - pybamm.models.submodels
    - pybamm.models.submodels.convection
    - pybamm.models.submodels.convection.through_cell
    - pybamm.models.submodels.convection.transverse
    - pybamm.models.submodels.current_collector
    - pybamm.models.submodels.electrode
    - pybamm.models.submodels.electrode.ohm
    - pybamm.models.submodels.electrolyte_conductivity
    - pybamm.models.submodels.electrolyte_conductivity.surface_potential_form
    - pybamm.models.submodels.electrolyte_diffusion
    - pybamm.models.submodels.external_circuit
    - pybamm.models.submodels.interface
    - pybamm.models.submodels.interface.first_order_kinetics
    - pybamm.models.submodels.interface.inverse_kinetics
    - pybamm.models.submodels.interface.kinetics
    - pybamm.models.submodels.interface.sei
    - pybamm.models.submodels.oxygen_diffusion
    - pybamm.models.submodels.particle
    - pybamm.models.submodels.porosity
    - pybamm.models.submodels.thermal
    - pybamm.models.submodels.thermal.pouch_cell
    - pybamm.models.submodels.tortuosity
    - pybamm.parameters
    - pybamm.plotting
    - pybamm.solvers
    - pybamm.solvers.c_solvers
    - pybamm.spatial_methods
  commands:
    - pybamm_edit_parameter --help
    - pybamm_add_parameter --help
    - pybamm_rm_parameter --help
    - pybamm_install_odes --help

about:
  home: https://github.com/pybamm-team/PyBaMM
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Battery Mathematical Modelling.
  doc_url: https://pybamm.readthedocs.io/en/latest
  dev_url: https://github.com/pybamm-team/PyBaMM

extra:
  recipe-maintainers:
    - priyanshuone6
    - tlestang
