{% set name = "pybamm" %}
{% set version = "22.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a9cfeeafe74eee9778dbba603e075df1c764dbac8f28edf7c19fd9ab2c48e5d

build:
  number: 0
  entry_points:
    - pybamm_edit_parameter = pybamm.parameters_cli:edit_parameter
    - pybamm_add_parameter = pybamm.parameters_cli:add_parameter
    - pybamm_rm_parameter = pybamm.parameters_cli:remove_parameter
    - pybamm_install_odes = pybamm.install_odes:main
    - pybamm_install_jax = pybamm.util:install_jax
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [py<37 or py>=310]

requirements:
  host:
    - pip
    - python
    - wheel
  run:
    - anytree >=2.4.3
    - autograd >=1.2
    - casadi >=3.5.0
    - imageio >=2.9.0
    - jupyter
    - matplotlib-base >=2.0
    - numpy >=1.16
    - pandas >=0.24
    - pybtex
    - python
    - scikit-fem >=0.2.0
    - scipy >=1.3
    - sympy ==1.9

test:
  imports:
    - pybamm
    - pybamm.discretisations
    - pybamm.experiments
    - pybamm.expression_tree
    - pybamm.expression_tree.operations
    - pybamm.expression_tree.printing
    - pybamm.geometry
    - pybamm.meshes
    - pybamm.models
    - pybamm.models.full_battery_models
    - pybamm.models.full_battery_models.lead_acid
    - pybamm.models.full_battery_models.lithium_ion
    #- pybamm.models.full_battery_models.lithium_metal (next release)
    - pybamm.models.submodels
    - pybamm.models.submodels.active_material
    - pybamm.models.submodels.convection
    - pybamm.models.submodels.convection.through_cell
    - pybamm.models.submodels.convection.transverse
    - pybamm.models.submodels.current_collector
    - pybamm.models.submodels.electrode
    - pybamm.models.submodels.electrode.ohm
    - pybamm.models.submodels.electrolyte_conductivity
    - pybamm.models.submodels.electrolyte_conductivity.surface_potential_form
    - pybamm.models.submodels.electrolyte_diffusion
    - pybamm.models.submodels.external_circuit
    - pybamm.models.submodels.interface
    - pybamm.models.submodels.interface.interface_utilisation
    - pybamm.models.submodels.interface.kinetics
    - pybamm.models.submodels.interface.kinetics.first_order_kinetics
    - pybamm.models.submodels.interface.kinetics.inverse_kinetics
    - pybamm.models.submodels.interface.lithium_plating
    - pybamm.models.submodels.interface.sei
    - pybamm.models.submodels.oxygen_diffusion
    - pybamm.models.submodels.particle
    - pybamm.models.submodels.particle.no_distribution
    - pybamm.models.submodels.particle.size_distribution
    - pybamm.models.submodels.particle_mechanics
    - pybamm.models.submodels.porosity
    - pybamm.models.submodels.thermal
    - pybamm.models.submodels.thermal.pouch_cell
    - pybamm.models.submodels.transport_efficiency
    - pybamm.parameters
    - pybamm.plotting
    - pybamm.solvers
    - pybamm.solvers.c_solvers
    - pybamm.spatial_methods
  commands:
    - pybamm_edit_parameter --help
    - pybamm_add_parameter --help
    - pybamm_rm_parameter --help
    - pybamm_install_odes --help  # [not win]
    - pybamm_install_jax --help

about:
  home: https://github.com/pybamm-team/PyBaMM
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Battery Mathematical Modelling.
  doc_url: https://pybamm.readthedocs.io/en/latest
  dev_url: https://github.com/pybamm-team/PyBaMM

extra:
  recipe-maintainers:
    - priyanshuone6
    - tlestang
