schema_version: 1

context:
  name: pybamm
  version: "26.5.0"

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8b1fe25c5a6f67e9d6782194a73fdc272f196eadbf717d9f56f49b1464231843

build:
  number: 0

outputs:
  - package:
      name: pybamm-base
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - hatchling >=1.13.0
        - hatch-vcs >=0.3.0
      run:
        - python >=${{ python_min }}
        - posthog
        - black
        - numpy
        - pandas >=1.5.0
        - scipy >=1.11.4
        - sympy >=1.12
        - typing-extensions >=4.10.0
        - xarray >=2022.6.0
        - pooch
        - pyyaml
        - platformdirs
        - pybammsolvers >=0.8.0,<0.9.0
    tests:
      - python:
          imports:
            - pybamm
            - pybamm.codegen
            - pybamm.discretisations
            - pybamm.dispatch
            - pybamm.experiment
            - pybamm.experiment.step
            - pybamm.experiment.experiment
            - pybamm.expression_tree
            - pybamm.expression_tree.operations
            - pybamm.expression_tree.printing
            - pybamm.geometry
            - pybamm.input
            - pybamm.inpu.parameters
            - pybamm.meshes
            - pybamm.models
            - pybamm.models.full_battery_models
            - pybamm.models.full_battery_models.equivalent_circuit
            - pybamm.models.full_battery_models.lead_acid
            - pybamm.models.full_battery_models.lithium_ion
            # See https://github.com/pybamm-team/PyBaMM/issues/1905
            # - pybamm.models.full_battery_models.lithium_metal
            - pybamm.models.full_battery_models.sodium_ion
            - pybamm.models.submodels
            - pybamm.models.submodels.active_material
            - pybamm.models.submodels.convection
            - pybamm.models.submodels.convection.through_cell
            - pybamm.models.submodels.convection.transverse
            - pybamm.models.submodels.current_collector
            - pybamm.models.submodels.electrode
            - pybamm.models.submodels.electrode.ohm
            - pybamm.models.submodels.electrolyte_conductivity
            - pybamm.models.submodels.electrolyte_conductivity.surface_potential_form
            - pybamm.models.submodels.electrolyte_diffusion
            - pybamm.models.submodels.equivalent_circuit_elements
            - pybamm.models.submodels.external_circuit
            - pybamm.models.submodels.interface
            - pybamm.models.submodels.interface.interface_utilisation
            - pybamm.models.submodels.interface.kinetics
            - pybamm.models.submodels.interface.kinetics.inverse_kinetics
            - pybamm.models.submodels.interface.lithium_plating
            - pybamm.models.submodels.interface.open_circuit_potential
            - pybamm.models.submodels.interface.sei
            - pybamm.models.submodels.oxygen_diffusion
            - pybamm.models.submodels.particle
            - pybamm.models.submodels.particle_mechanics
            - pybamm.models.submodels.porosity
            - pybamm.models.submodels.thermal
            - pybamm.models.submodels.thermal.pouch_cell
            - pybamm.models.submodels.thermal.surface
            - pybamm.models.submodels.transport_efficiency
            - pybamm.parameters
            - pybamm.plotting
            - pybamm.simulation
            - pybamm.solvers
            - pybamm.spatial_methods
      - requirements:
          run:
            - python ${{ python_min }}.*
            - pip
        script:
          - pip check

  - package:
      name: pybamm
    build:
      noarch: python

    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools >=64
      run:
        - ${{ pin_subpackage('pybamm-base', exact=True) }}
        - python >=${{ python_min }}
        # Battery Parameter eXchange format
        - bpx >=1.1.0,<1.2.0
        # Progress bars
        - tqdm
        # Plotting
        - matplotlib-base >=3.6.0
        # Cite
        - pybtex >=0.25.0
        # JAX
        - if: match(python, ">=3.11")
          then: jax >=0.7.0,<0.9.0
        # Other dependencies
        - scikit-fem >=8.1.0
        - meshio >=5.3.0

    tests:
      - python:
          imports:
            - pybamm
            - pybamm.codegen
            - pybamm.discretisations
            - pybamm.dispatch
            - pybamm.experiment
            - pybamm.experiment.step
            - pybamm.experiment.experiment
            - pybamm.expression_tree
            - pybamm.expression_tree.operations
            - pybamm.expression_tree.printing
            - pybamm.geometry
            - pybamm.input
            - pybamm.inpu.parameters
            - pybamm.meshes
            - pybamm.models
            - pybamm.models.full_battery_models
            - pybamm.models.full_battery_models.equivalent_circuit
            - pybamm.models.full_battery_models.lead_acid
            - pybamm.models.full_battery_models.lithium_ion
            # See https://github.com/pybamm-team/PyBaMM/issues/1905
            # - pybamm.models.full_battery_models.lithium_metal
            - pybamm.models.full_battery_models.sodium_ion
            - pybamm.models.submodels
            - pybamm.models.submodels.active_material
            - pybamm.models.submodels.convection
            - pybamm.models.submodels.convection.through_cell
            - pybamm.models.submodels.convection.transverse
            - pybamm.models.submodels.current_collector
            - pybamm.models.submodels.electrode
            - pybamm.models.submodels.electrode.ohm
            - pybamm.models.submodels.electrolyte_conductivity
            - pybamm.models.submodels.electrolyte_conductivity.surface_potential_form
            - pybamm.models.submodels.electrolyte_diffusion
            - pybamm.models.submodels.equivalent_circuit_elements
            - pybamm.models.submodels.external_circuit
            - pybamm.models.submodels.interface
            - pybamm.models.submodels.interface.interface_utilisation
            - pybamm.models.submodels.interface.kinetics
            - pybamm.models.submodels.interface.kinetics.inverse_kinetics
            - pybamm.models.submodels.interface.lithium_plating
            - pybamm.models.submodels.interface.open_circuit_potential
            - pybamm.models.submodels.interface.sei
            - pybamm.models.submodels.oxygen_diffusion
            - pybamm.models.submodels.particle
            - pybamm.models.submodels.particle_mechanics
            - pybamm.models.submodels.porosity
            - pybamm.models.submodels.thermal
            - pybamm.models.submodels.thermal.pouch_cell
            - pybamm.models.submodels.thermal.surface
            - pybamm.models.submodels.transport_efficiency
            - pybamm.parameters
            - pybamm.plotting
            - pybamm.simulation
            - pybamm.solvers
            - pybamm.spatial_methods
      - requirements:
          run:
            - python ${{ python_min }}.*
            - pip
        script:
          - pip check

about:
  homepage: https://pybamm.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python Battery Mathematical Modelling

extra:
  recipe-maintainers:
    - valentinsulzer
    - Saransh-cpp
    - agriyakhetarpal
    - priyanshuone6
    - tlestang
