github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
conda_build_tool: rattler-build
